// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6IWi4Of7MqgSVanMibX1RwNqgVQTKGs',
    appId: '1:1096094668399:web:364fb3e4a0401907e9df9a',
    messagingSenderId: '1096094668399',
    projectId: 'cda-rpto-app',
    authDomain: 'cda-rpto-app.firebaseapp.com',
    storageBucket: 'cda-rpto-app.firebasestorage.app',
    measurementId: 'G-WCEC3PZ9EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcHnO-zfx-5Ujl-jXOYal6AoKFYjJoT-g',
    appId: '1:1096094668399:android:68d1661620d9bb6ce9df9a',
    messagingSenderId: '1096094668399',
    projectId: 'cda-rpto-app',
    storageBucket: 'cda-rpto-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwXlhJMMDbIFF5vu62YxdTa97VyQjIZ1Y',
    appId: '1:1096094668399:ios:e6a790e5af994d9ee9df9a',
    messagingSenderId: '1096094668399',
    projectId: 'cda-rpto-app',
    storageBucket: 'cda-rpto-app.firebasestorage.app',
    iosBundleId: 'com.example.cdaRptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwXlhJMMDbIFF5vu62YxdTa97VyQjIZ1Y',
    appId: '1:1096094668399:ios:e6a790e5af994d9ee9df9a',
    messagingSenderId: '1096094668399',
    projectId: 'cda-rpto-app',
    storageBucket: 'cda-rpto-app.firebasestorage.app',
    iosBundleId: 'com.example.cdaRptoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6IWi4Of7MqgSVanMibX1RwNqgVQTKGs',
    appId: '1:1096094668399:web:e77de4bdf630b59fe9df9a',
    messagingSenderId: '1096094668399',
    projectId: 'cda-rpto-app',
    authDomain: 'cda-rpto-app.firebaseapp.com',
    storageBucket: 'cda-rpto-app.firebasestorage.app',
    measurementId: 'G-CHB59QTCVE',
  );
}
